version: '2.1'

services:

  series-api:
    image: webapi:latest  
    container_name: series-api
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - "5000:80" 
      - "5001:443" 
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - series-seq

  postgres:
    image: postgres:latest
    container_name: series-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: 130898 
      POSTGRES_DB: Series  
    ports:
      - "5432:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data 

  series-seq:
    image: datalust/seq:latest 
    container_name: series-seq
    environment:
      ACCEPT_EULA: Y  
    ports:
      - "5341:5341" 
      - "8081:80"
    volumes:
      - seq_data:/data 

volumes:
  pg_data: 
  seq_data:  